#!/bin/bash
CURRENT_FILE="$(realpath "${BASH_SOURCE[0]}")"
DOTFILE_HOME="$(dirname "$CURRENT_FILE")"
DOTFILE_HOME=$HOME/.dotfiles

function installEverything() {
  # Python and pip
  if ! type "pip" ; then
    echo "Installing Python / pip..."
    sudo apt update
    sudo apt install python3
    python -m ensurepip --upgrade
  fi

  # Ansible
  if ! type "ansible" ; then
    echo "Installing Ansible..."
    python3 -m pip install --user ansible
  fi

    # neovim nightly
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x nvim.appimage
    mv nvim.appimage $HOME/.local/bin/nvim

    # tsserver lsp
    npm i -g typescript-language-server

    # other dependencies
    sudo apt install ripgrep tmux zsh

    # oh my zsh
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    # lsd
    cargo install lsd

    sudo apt install zoxide
}

if [[ "$1" == "install" ]]; then
    installEverything
fi

pushd $DOTFILE_HOME
PACKAGES="alacritty nvim tmux zshrc git"
for PACKAGE in $PACKAGES; do
  stow -D $PACKAGE
  stow $PACKAGE
done
popd

# manual links
CONFIG_DIR=$HOME/.config

ln -s $DOTFILE_HOME/i3/config $CONFIG_DIR/i3/
ln -s $DOTFILE_HOME/polybar/* $CONFIG_DIR/polybar/
