#!/bin/bash
DOTFILE_HOME=$HOME/.dotfiles

# neovim nightly
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
mv nvim.appimage $HOME/.local/bin/nvim

# tsserver lsp
npm i -g typescript-language-server

# other dependencies
sudo apt install ripgrep tmux zsh

# oh my zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

pushd $DOTFILE_HOME
PACKAGES="alacritty nvim tmux zshrc"
for PACKAGE in $PACKAGES; do
  stow -D $PACKAGE
  stow $PACKAGE
done
popd

